name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      # Conditionally skip tests based on an environment variable
      - name: Run Tests
        if: ${{ secrets.SKIP_TESTS != 'true' }}  # Skip tests if SKIP_TESTS secret is set to 'true'
        run: |
          . venv/bin/activate
          python -m unittest discover -s tests

  docker-build-push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t twistedorc/flask-app:latest .
          docker push twistedorc/flask-app:latest

